name: Test Python App
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Installer les dépendances
        run: pip install pytest

      - name: Exécuter les tests
        run: python -m unittest test_app.py

  security:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Installer SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          echo "$PWD/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      - name: Analyse du code avec SonarQube
        run: |
          sonar-scanner \
          -Dsonar.organization=serena-lydie \
          -Dsonar.projectKey=serena-lydie_tp-ci-cd \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=${{secrets.SONAR_TOKEN}}

      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deploy: 
    needs: test 
    runs-on: ubuntu-latest 
    steps: 
      - name: Déclencher le déploiement sur Render 
        run: | 
          curl -X POST "https://api.render.com/deploy/srv-cvhurhqn91rc73aj30vg?key=TCZdL0k0oVc"
